
  name: wifijammer
  version: '2.2' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Wifi Jammer is used to jam the neiboring wifi connections around you.
  description: |
    Wifi Jammer is used to jam the wifi network, including the surrounding internal IP devices connected to the same device.

  grade: 'stable'
  confinement: 'strict'

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
